apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # deployment labels
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      component: database
  template:
    metadata:
    labels:
      component: mongodb
      project: roboshop
      tier: database
  spec:
    containers:
    - name: mongodb
      image: raghu73/mongodb:v1


---


      
